<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NHUTBM" name="Function Login" tests="1" failures="1" timestamp="20 Aug 2020 03:50:19 GMT" time="12.448" errors="0">
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="com.testcase.LogInScript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at CommonPage.CommonTestcase.getResult(CommonTestcase.java:107)
	at com.testcase.LogInScript.afterMethod(LogInScript.java:63)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="@AfterClass afterClass" time="0.0" classname="com.testcase.LogInScript">
    <skipped/>
  </testcase> <!-- @AfterClass afterClass -->
  <testcase name="testcase_01_Dont_input_username_password" time="0.006" classname="com.testcase.LogInScript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at CommonPage.CommonTestcase.logTestCase(CommonTestcase.java:102)
	at com.testcase.LogInScript.testcase_01_Dont_input_username_password(LogInScript.java:49)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testcase_01_Dont_input_username_password -->
</testsuite> <!-- Function Login -->
